# This workflow formats R code using the air standard via rstudio/shiny-workflows/format-r-code
# See: https://www.tidyverse.org/blog/2025/02/air/#fn:1
# and: https://github.com/rstudio/shiny-workflows/tree/main/format-r-code

name: Format R code

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format R code
        uses: rstudio/shiny-workflows/format-r-code@v1
