#' @title Align column names and choices to match standard HESPER names compatible with heseR package
#'
#'
#'
#'
#'
#'
#'
align_hesper_data <- function(
    data,
    hesper_drinking_water = "hesper_drinking_water",
    hesper_food = "hesper_food",
    hesper_shelter = "hesper_shelter",
    hesper_toilet = "hesper_toilet",
    hesper_clean = "hesper_clean",
    hesper_clean_female = "hesper_clean_female",
    hesper_clothes_etc = "hesper_clothes_etc",
    hesper_income_livelihood = "hesper_income_livelihood",
    hesper_health = "hesper_health",
    hesper_health_care_male = "hesper_health_care_male",
    hesper_health_care_female = "hesper_health_care_female",
    hesper_distress = "hesper_distress",
    hesper_safety = "hesper_safety",
    hesper_education = "hesper_education",
    hesper_care = "hesper_care",
    hesper_support = "hesper_support",
    hesper_separation = "hesper_separation",
    hesper_displaced = "hesper_displaced",
    hesper_information = "hesper_information",
    hesper_aid = "hesper_aid",
    hesper_respect = "hesper_respect",
    hesper_movement = "hesper_movement",
    hesper_time = "hesper_time",
    hesper_law = "hesper_law",
    hesper_gbv = "hesper_gbv",
    hesper_drug = "hesper_drug",
    hesper_mental_health = "hesper_mental_health",
    hesper_care_community = "hesper_care_community",
    hesper_other = "hesper_other",
    hesper_clean_male = NULL, ## if individual level HESPER, standard name and item is hesper_clean_male, and replaces hesper_clean

    hesper_priority_first="hesper_priority_first",
    hesper_priority_second="hesper_priority_second",
    hesper_priority_third="hesper_priority_third",

    hesper_drinking_water_choice = "hesper_drinking_water",
    hesper_food_choice = "hesper_food",
    hesper_shelter_choice = "hesper_shelter",
    hesper_toilet_choice = "hesper_toilet",
    hesper_clean_choice = "hesper_clean",
    hesper_clean_female_choice = "hesper_clean_female",
    hesper_clothes_etc_choice = "hesper_clothes_etc",
    hesper_income_livelihood_choice = "hesper_income_livelihood",
    hesper_health_choice = "hesper_health",
    hesper_health_care_male_choice = "hesper_health_care_male",
    hesper_health_care_female_choice = "hesper_health_care_female",
    hesper_distress_choice = "hesper_distress",
    hesper_safety_choice = "hesper_safety",
    hesper_education_choice = "hesper_education",
    hesper_care_choice = "hesper_care",
    hesper_support_choice = "hesper_support",
    hesper_separation_choice = "hesper_separation",
    hesper_displaced_choice = "hesper_displaced",
    hesper_information_choice = "hesper_information",
    hesper_aid_choice = "hesper_aid",
    hesper_respect_choice = "hesper_respect",
    hesper_movement_choice = "hesper_movement",
    hesper_time_choice = "hesper_time",
    hesper_law_choice = "hesper_law",
    hesper_gbv_choice = "hesper_gbv",
    hesper_drug_choice = "hesper_drug",
    hesper_mental_health_choice = "hesper_mental_health",
    hesper_care_community_choice = "hesper_care_community",
    hesper_other_choice = "hesper_other",
    hesper_clean_male_choice = NULL

){


  ## Define the above vector in the same way, but name it with the same names
  hesper_vars <- c(
    "hesper_drinking_water" = hesper_drinking_water,
    "hesper_food" = hesper_food,
    "hesper_shelter" = hesper_shelter,
    "hesper_toilet" = hesper_toilet,
    "hesper_clean" = hesper_clean,
    "hesper_clean_female" = hesper_clean_female,
    "hesper_clothes_etc" = hesper_clothes_etc,
    "hesper_income_livelihood" = hesper_income_livelihood,
    "hesper_health" = hesper_health,
    "hesper_health_care_male" = hesper_health_care_male,
    "hesper_health_care_female" = hesper_health_care_female,
    "hesper_distress" = hesper_distress,
    "hesper_safety" = hesper_safety,
    "hesper_education" = hesper_education,
    "hesper_care" = hesper_care,
    "hesper_support" = hesper_support,
    "hesper_separation" = hesper_separation,
    "hesper_displaced" = hesper_displaced,
    "hesper_information" = hesper_information,
    "hesper_aid" = hesper_aid,
    "hesper_respect" = hesper_respect,
    "hesper_movement" = hesper_movement,
    "hesper_time" = hesper_time,
    "hesper_law" = hesper_law,
    "hesper_gbv" = hesper_gbv,
    "hesper_drug" = hesper_drug,
    "hesper_mental_health" = hesper_mental_health,
    "hesper_care_community" = hesper_care_community,
    "hesper_other" = hesper_other,
    "hesper_clean_male" = hesper_clean_male
  )

  ## Same for the choices
  hesper_choices <- c(
    "hesper_drinking_water" = hesper_drinking_water_choice,
    "hesper_food" = hesper_food_choice,
    "hesper_shelter" = hesper_shelter_choice,
    "hesper_toilet" = hesper_toilet_choice,
    "hesper_clean" = hesper_clean_choice,
    "hesper_clean_female" = hesper_clean_female_choice,
    "hesper_clothes_etc" = hesper_clothes_etc_choice,
    "hesper_income_livelihood" = hesper_income_livelihood_choice,
    "hesper_health" = hesper_health_choice,
    "hesper_health_care_male" = hesper_health_care_male,
    "hesper_health_care_female" = hesper_health_care_female,
    "hesper_distress" = hesper_distress_choice,
    "hesper_safety" = hesper_safety_choice,
    "hesper_education" = hesper_education_choice,
    "hesper_care" = hesper_care_choice,
    "hesper_support" = hesper_support_choice,
    "hesper_separation" = hesper_separation_choice,
    "hesper_displaced" = hesper_displaced_choice,
    "hesper_information" = hesper_information_choice,
    "hesper_aid" = hesper_aid_choice,
    "hesper_respect" = hesper_respect_choice,
    "hesper_movement" = hesper_movement_choice,
    "hesper_time" = hesper_time_choice,
    "hesper_law" = hesper_law_choice,
    "hesper_gbv" = hesper_gbv_choice,
    "hesper_drug" = hesper_drug_choice,
    "hesper_mental_health" = hesper_mental_health_choice,
    "hesper_care_community" = hesper_care_community_choice,
    "hesper_other" = hesper_other_choice,
    "hesper_clean_male" = hesper_clean_male
  )

  ### combine all the column name parameters into hesper_vars
  hesper_vars <- c(hesper_drinking_water,
                   hesper_food,
                   hesper_shelter,
                   hesper_toilet,
                   hesper_clean,
                   hesper_clean_female,
                   hesper_clothes_etc,
                   hesper_income_livelihood,
                   hesper_health,
                   hesper_health_care_male,
                   hesper_health_care_female,
                   hesper_distress,
                   hesper_safety,
                   hesper_education,
                   hesper_care,
                   hesper_support,
                   hesper_separation,
                   hesper_displaced,
                   hesper_information,
                   hesper_aid,
                   hesper_respect,
                   hesper_movement,
                   hesper_time,
                   hesper_law,
                   hesper_gbv,
                   hesper_drug,
                   hesper_mental_health,
                   hesper_care_community,
                   hesper_other,
                   hesper_clean_male)


  ### combine all the column name parameters into hesper_choices
  hesper_choices <- c(hesper_drinking_water_choice,
                      hesper_food_choice,
                      hesper_shelter_choice,
                      hesper_toilet_choice,
                      hesper_clean_choice,
                      hesper_clean_female_choice,
                      hesper_clothes_etc_choice,
                      hesper_income_livelihood_choice,
                      hesper_health_choice,
                      hesper_health_care_male_choice,
                      hesper_health_care_female_choice,
                      hesper_distress_choice,
                      hesper_safety_choice,
                      hesper_education_choice,
                      hesper_care_choice,
                      hesper_support_choice,
                      hesper_separation_choice,
                      hesper_displaced_choice,
                      hesper_information_choice,
                      hesper_aid_choice,
                      hesper_respect_choice,
                      hesper_movement_choice,
                      hesper_time_choice,
                      hesper_law_choice,
                      hesper_gbv_choice,
                      hesper_drug_choice,
                      hesper_mental_health_choice,
                      hesper_care_community_choice,
                      hesper_other_choice,
                      hesper_clean_male_choice)

  ### Identify the differing column names i.e. when the parameter differ from its default value


}
