# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  issue_comment:
    types: [created]

name: pr-commands.yaml

permissions: read-all

jobs:
  document:
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/document') }}
    name: document
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libfribidi-dev \
            libharfbuzz-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libcairo2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libsodium-dev \
            libmagick++-dev \
            libicu-dev \
            libudunits2-dev \
            libglpk-dev \
            libglpk40 \
            zlib1g-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          needs: pr-document

      # - name: Enable pak in renv
      #   run: Rscript -e 'options(renv.config.pak.enabled = TRUE)'

      - name: Restore R dependencies from renv.lock
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          renv-lockfile: renv.lock
          renv-project: .
          # repos: 'c(CRAN = "https://p3m.dev/cran/__linux__/manylinux_2_28/latest")'

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: commit
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE
          git commit -m 'Document'

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# Style is done via Air workflow
# style:
#   if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/style') }}
#   name: style
#   runs-on: ubuntu-latest
#   env:
#     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#   permissions:
#     contents: write
#   steps:
#     - uses: actions/checkout@v4

#     - uses: r-lib/actions/pr-fetch@v2
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}

#     - uses: r-lib/actions/setup-r@v2

#     - name: Install dependencies
#       run: install.packages("styler")
#       shell: Rscript {0}

#     - name: Style
#       run: styler::style_pkg()
#       shell: Rscript {0}

#     - name: commit
#       run: |
#         git config --local user.name "$GITHUB_ACTOR"
#         git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
#         git add \*.R
#         git commit -m 'Style'

#     - uses: r-lib/actions/pr-push@v2
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
